services:
  database:
    container_name: encurta-ai_db
    image: postgres:17.5-alpine3.22
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=pass
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: encurta-ai_app
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./config:/usr/app/config
    ports:
      - "5150:5150"
    command: start -s  
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      

volumes:
  postgres-data:
