services:
  database:
    container_name: encurta-ai_db
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=pass
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s      
  app:
    container_name: encurta-ai_app
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./config:/usr/app/config
    ports:
      - "5150:5150"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: start -s -e production      
    networks:
      - database
      - app

volumes:
  postgres-data:

networks:
  app:
    driver: bridge
  database:
    driver: bridge    

